### ISSUE TITLE
Mod loader crashing on startup

### ISSUE THREAD

**Issue by cmaresh** [solimodsthings/hs-mod-loader#1]
Loader crashes right away without displaying a window. "GameFolderPath" in config.json has been set to the Himeko Sutori folder in steamapps/common.

Occurring on a Windows 10 computer. Validating game files doesn't seem to fix it. No screenshots available.

**Comment by solimodsthings** [comment]
@cmaresh thanks for letting me know

A few questions that will help me troubleshoot:
1. Does it surface any error messages when it crashes? Or is it completely silent?
2. Is the Loader being launched from the green Himeko Sutori 'play' button in Steam?

**Comment by cmaresh** [comment]
I'm not getting any errors, it crashes silently.

Yeah, I'm launching it from the green button

**Comment by solimodsthings** [comment]
The '...\steamapps\common\Himeko Sutori\Binaries\ModLoader' folder is where the Loader executable lives. It will crash silently if the corresponding config file doesn't exist. Does your folder look something like this?

![image](https://user-images.githubusercontent.com/85382851/161332901-24db4840-3472-4866-9579-4e68ad240e5e.png)

**Comment by cmaresh** [comment]
![image](https://user-images.githubusercontent.com/5368740/161333321-7dab6db5-694f-4090-96fe-f6095f50466a.png)

Mod loader config looks like it is there for me

**Comment by solimodsthings** [comment]
Ok fantastic! The Loader uses .NET 4.7.2 to run which is included with the game through Steamworks Common Redistributables. When you have a chance, can we check if that exists on your machine?

In '...\steamapps\common\Steamworks Shared\_CommonRedist\DotNet' there should be a folder for .NET 4.7:
![image](https://user-images.githubusercontent.com/85382851/161336646-d5d6495e-589e-4507-b318-2e899eb2f313.png)

**Comment by cmaresh** [comment]
Yep, no problem. Folder for .NET 4.7 is there as well:
![image](https://user-images.githubusercontent.com/5368740/161340374-ca59b6e7-fccf-425e-9dda-1461cd1db154.png)

**Comment by solimodsthings** [comment]
I'm wondering if we can take a peek in your Event Viewer... The app is crashing silently, but there should still be a stack trace recorded in there

In Event Viewer, click on Windows Logs > Application:
![image](https://user-images.githubusercontent.com/85382851/161340773-394b9ef3-aeea-4a00-9150-ef1c10c06ef7.png)

It might take a few seconds for the logs to load. Do any .NET runtime errors appear? Might look like this:
![image](https://user-images.githubusercontent.com/85382851/161341005-27859f9f-1466-46f3-b275-2af98c851118.png)

If you double-click on the error, it should display full stack trace like this:
![image](https://user-images.githubusercontent.com/85382851/161341182-c2d98bde-eadf-4898-be58-9c0413b5708a.png)

Can you share the error log and stack trace, if it exists?

**Comment by cmaresh** [comment]
I'm getting this .NET error when trying to open it up:
[modloader_dotneterror.txt](https://github.com/solimodsthings/hs-mod-loader/files/8400959/modloader_dotneterror.txt)

**Comment by solimodsthings** [comment]
@cmaresh Thanks that was very helpful

Short story: 
I've prepared a [v1.2.1 hotfix](https://github.com/solimodsthings/hs-mod-loader/releases/download/v1.2.1-hotfix) for you. Can you place [this HSModLoader.exe](https://github.com/solimodsthings/hs-mod-loader/releases/download/v1.2.1-hotfix/HSModLoader.exe) file in your '...\steamapps\common\Himeko Sutori\Binaries\ModLoader' folder and try running the Loader from Steam?

When you launch it you will see the version number in the window title:
![image](https://user-images.githubusercontent.com/85382851/161351779-7f0bd9a4-8df4-4724-b7b7-d9f6c3cbe82f.png)

Long story:
The Loader uses [FileSystemWatcher](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-6.0) to detect newly subscribed mods. This is so it can automatically rebuild the mod list whenever a new mod appears in Himeko Sutori's Steam Workshop download folder. The app is crashing because it can't seem to watch Himeko Sutori's Workshop folder. Maybe it is security permissions or folder availability or something else, but the app shouldn't crash in its entirety so v1.2.1 now has safeguards put in place to leave that feature disabled if it encounters a problem. If the fix works for you, I will include it in the upcoming v1.3 release.

https://github.com/solimodsthings/hs-mod-loader/releases/download/v1.2.1-hotfix/HSModLoader.exe

**Comment by cmaresh** [comment]
1.2.1 is crashing for me silently as well. Here's the error and stack trace from the event viewer:
[modloader1.2.1_dotneterror.txt](https://github.com/solimodsthings/hs-mod-loader/files/8401580/modloader1.2.1_dotneterror.txt)

**Comment by solimodsthings** [comment]
Thanks for giving it a shot and including the stack trace! Give this [new v1.2.1b HSModLoader.exe](https://github.com/solimodsthings/hs-mod-loader/releases/download/v1.2.1b-hotfix/HSModLoader.exe) a chance when you have time

**Comment by cmaresh** [comment]
That looks like it did it, thank you! Mod loader is opening with no errors

**Comment by solimodsthings** [comment]
Excellent!! I will include this hotfix in the next major release. It will be a normal update through Steam. Thanks for testing!
